import { Head, Link } from "@inertiajs/react";
import { AlertTriangle, CalendarClock, MapPin, School, UserCheck, UsersRound } from "lucide-react";
import { InstructorLayout } from "@/layouts/instructor-layout";
import { StatCard } from "@/components/stat-card";
import { Button } from "@/components/ui/button";

interface TrainingClass { id: number; name: string; room: string | null; enrollments_count: number; training_batch: { name: string; training_program: { name: string } } }
interface Schedule { id: number; schedule_date: string; start_time: string; end_time: string; subject: string | null; training_class: { id: number; name: string; room: string | null }; attendance_location: { name: string } | null }
export default function Dashboard({ classes, todaySchedules, stats }: { classes: TrainingClass[]; todaySchedules: Schedule[]; stats: { classes: number; participants: number; presentToday: number; needsReview: number } }) { return <InstructorLayout title="Ringkasan kelas"><Head title="Dashboard Instruktur" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Kelas" value={stats.classes} icon={School} /><StatCard label="Peserta" value={stats.participants} icon={UsersRound} /><StatCard label="Hadir hari ini" value={stats.presentToday} icon={UserCheck} tone="green" /><StatCard label="Perlu ditinjau" value={stats.needsReview} icon={AlertTriangle} tone="red" /></div><section className="mt-6"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-lg font-bold">Jadwal mengajar hari ini</h2><CalendarClock className="size-5 text-primary" /></div><div className="grid gap-3 lg:grid-cols-2">{todaySchedules.map(schedule => <article key={schedule.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{schedule.subject || "Pelatihan"}</p><p className="text-sm text-muted-foreground">{schedule.training_class.name} · {schedule.training_class.room || "Ruang belum ditentukan"}</p></div><span className="rounded-lg bg-blue-50 px-3 py-1 text-sm font-semibold text-primary">{schedule.start_time.slice(0, 5)}–{schedule.end_time.slice(0, 5)}</span></div><p className="mt-3 flex items-center gap-2 text-sm"><MapPin className="size-4 text-primary" />{schedule.attendance_location?.name || "Lokasi belum ditentukan"}</p><Button asChild variant="outline" className="mt-4"><Link href={route("instructor.attendances.index", { class_id: schedule.training_class.id, date: schedule.schedule_date })}>Pantau absensi</Link></Button></article>)}{todaySchedules.length === 0 && <div className="rounded-2xl border border-dashed bg-white p-8 text-center text-muted-foreground lg:col-span-2">Tidak ada jadwal mengajar hari ini.</div>}</div></section><section className="mt-6 grid gap-3 sm:grid-cols-2"><h2 className="text-lg font-bold sm:col-span-2">Kelas yang ditugaskan</h2>{classes.map(item => <article key={item.id} className="rounded-2xl border bg-white p-5"><p className="text-sm text-primary">{item.training_batch.training_program.name} · {item.training_batch.name}</p><h3 className="mt-1 text-lg font-bold">{item.name}</h3><p className="mt-2 text-sm text-muted-foreground">{item.enrollments_count} peserta · Ruang {item.room || "-"}</p><Button asChild className="mt-4" variant="outline"><Link href={route("instructor.classes.show", item.id)}>Kelola kelas</Link></Button></article>)}{classes.length === 0 && <div className="rounded-xl border bg-white p-10 text-center text-muted-foreground sm:col-span-2">Belum ada kelas yang ditugaskan.</div>}</section></InstructorLayout>; }
