<?php

use App\Http\Controllers\Admin\ActivityLogController;
use App\Http\Controllers\Admin\AnnouncementController;
use App\Http\Controllers\Admin\AttendanceController as AdminAttendanceController;
use App\Http\Controllers\Admin\AttendanceLocationController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\FraudFlagController;
use App\Http\Controllers\Admin\HolidayController;
use App\Http\Controllers\Admin\InstructorController;
use App\Http\Controllers\Admin\LeaveRequestController as AdminLeaveRequestController;
use App\Http\Controllers\Admin\ParticipantController;
use App\Http\Controllers\Admin\ParticipantImportController;
use App\Http\Controllers\Admin\ParticipantVerificationController;
use App\Http\Controllers\Admin\RegistrationCodeController;
use App\Http\Controllers\Admin\ReportController;
use App\Http\Controllers\Admin\RolePermissionController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TrainingBatchController;
use App\Http\Controllers\Admin\TrainingClassController;
use App\Http\Controllers\Admin\TrainingProgramController;
use App\Http\Controllers\Admin\TrainingScheduleController;
use App\Http\Controllers\Admin\UserManagementController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AttendancePhotoController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\BrandLogoController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Instructor\ClassController as InstructorClassController;
use App\Http\Controllers\Instructor\DashboardController as InstructorDashboardController;
use App\Http\Controllers\LeaveRequestController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\ParticipantScheduleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PwaIconController;
use App\Http\Controllers\PwaManifestController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

Route::get('/', function () {
    return Inertia::render('welcome');
})->name('home');
Route::get('/branding/logo', BrandLogoController::class)->name('brand.logo');
Route::get('/pwa/manifest.webmanifest', PwaManifestController::class)->name('pwa.manifest');
Route::get('/pwa/icon/{size}', PwaIconController::class)->whereIn('size', [192, 512])->name('pwa.icon');
Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->middleware('throttle:login');
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store'])->middleware('throttle:registration');
    Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])->name('password.request');
    Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])->middleware('throttle:3,1')->name('password.email');
    Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])->name('password.reset');
    Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.store');
});
Route::middleware(['auth', 'active'])->group(function (): void {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::put('/password', [PasswordController::class, 'update'])->name('password.update');
    Route::get('/password', [PasswordController::class, 'edit'])->name('password.edit');
    Route::get('/dashboard', DashboardController::class)->middleware('role:participant')->name('dashboard');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::patch('/notifications/read-all', [NotificationController::class, 'readAll'])->name('notifications.read-all');
    Route::patch('/notifications/{notification}', [NotificationController::class, 'read'])->name('notifications.read');
    Route::middleware('role:participant')->group(function (): void {
        Route::get('/attendance', [AttendanceController::class, 'create'])->name('attendance.create');
        Route::post('/attendance', [AttendanceController::class, 'store'])->middleware('throttle:10,1')->name('attendance.store');
        Route::get('/attendance/history', [AttendanceController::class, 'index'])->name('attendance.history');
        Route::get('/leave-requests', [LeaveRequestController::class, 'index'])->name('leave-requests.index');
        Route::post('/leave-requests', [LeaveRequestController::class, 'store'])->middleware('throttle:10,1')->name('leave-requests.store');
        Route::get('/schedule', ParticipantScheduleController::class)->name('schedule.index');
        Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
        Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    });
    Route::get('/leave-requests/{leaveRequest}/document', [LeaveRequestController::class, 'document'])->name('leave-requests.document');
    Route::get('/attendance-photos/{attendancePhoto}', AttendancePhotoController::class)->name('attendance-photos.show');
    Route::prefix('instructor')->name('instructor.')->middleware('role:instructor')->group(function (): void {
        Route::get('/', InstructorDashboardController::class)->name('dashboard');
        Route::get('classes/{trainingClass}', [InstructorClassController::class, 'show'])->name('classes.show');
    });
    Route::prefix('admin')->name('admin.')->middleware('role:super-admin|admin-ppkd')->group(function (): void {
        Route::get('/', AdminDashboardController::class)->name('dashboard');
        Route::resource('programs', TrainingProgramController::class)->parameters(['programs' => 'trainingProgram'])->middleware('role_permission:manage training master');
        Route::resource('batches', TrainingBatchController::class)->parameters(['batches' => 'trainingBatch'])->middleware('role_permission:manage training master');
        Route::resource('classes', TrainingClassController::class)->parameters(['classes' => 'trainingClass'])->middleware('role_permission:manage training master');
        Route::resource('instructors', InstructorController::class)->middleware('role_permission:manage users');
        Route::resource('schedules', TrainingScheduleController::class)->parameters(['schedules' => 'trainingSchedule'])->middleware('role_permission:manage training master');
        Route::resource('holidays', HolidayController::class)->middleware('role_permission:manage training master');
        Route::resource('locations', AttendanceLocationController::class)->parameters(['locations' => 'attendanceLocation'])->middleware('role_permission:manage training master');
        Route::get('verifications', [ParticipantVerificationController::class, 'index'])->middleware('role_permission:verify registrations')->name('verifications.index');
        Route::patch('verifications/{user}', [ParticipantVerificationController::class, 'update'])->middleware('role_permission:verify registrations')->name('verifications.update');
        Route::resource('participants', ParticipantController::class)->middleware('role_permission:manage participants');
        Route::resource('registration-codes', RegistrationCodeController::class)->parameters(['registration-codes' => 'registrationCode'])->except(['show'])->middleware('role_permission:manage training master');
        Route::get('leave-requests', [AdminLeaveRequestController::class, 'index'])->middleware('role_permission:process leave requests')->name('leave-requests.index');
        Route::patch('leave-requests/{leaveRequest}', [AdminLeaveRequestController::class, 'update'])->middleware('role_permission:process leave requests')->name('leave-requests.update');
        Route::get('attendances', [AdminAttendanceController::class, 'index'])->middleware('role_permission:monitor attendances')->name('attendances.index');
        Route::get('attendances/{attendance}', [AdminAttendanceController::class, 'show'])->middleware('role_permission:monitor attendances')->name('attendances.show');
        Route::patch('attendances/{attendance}', [AdminAttendanceController::class, 'update'])->middleware('role_permission:correct attendances')->name('attendances.update');
        Route::get('reports', [ReportController::class, 'index'])->middleware('role_permission:download reports')->name('reports.index');
        Route::get('reports/participants', [ReportController::class, 'participants'])->middleware('role_permission:download reports')->name('reports.participants');
        Route::get('reports/excel', [ReportController::class, 'excel'])->middleware('role_permission:download reports')->name('reports.excel');
        Route::get('reports/pdf', [ReportController::class, 'pdf'])->middleware('role_permission:download reports')->name('reports.pdf');
        Route::get('imports/participants', [ParticipantImportController::class, 'index'])->middleware('role_permission:manage participants')->name('imports.participants.index');
        Route::get('imports/participants/template', [ParticipantImportController::class, 'template'])->middleware('role_permission:manage participants')->name('imports.participants.template');
        Route::post('imports/participants/preview', [ParticipantImportController::class, 'preview'])->middleware('role_permission:manage participants')->name('imports.participants.preview');
        Route::post('imports/participants', [ParticipantImportController::class, 'store'])->middleware('role_permission:manage participants')->name('imports.participants.store');
        Route::get('settings', [SettingController::class, 'edit'])->name('settings.edit');
        Route::put('settings', [SettingController::class, 'update'])->name('settings.update');
        Route::get('activity-logs', ActivityLogController::class)->name('activity-logs.index');
        Route::get('users', [UserManagementController::class, 'index'])->name('users.index');
        Route::post('users', [UserManagementController::class, 'store'])->middleware('throttle:10,1')->name('users.store');
        Route::patch('users/{user}', [UserManagementController::class, 'update'])->name('users.update');
        Route::get('fraud-flags', [FraudFlagController::class, 'index'])->middleware('role_permission:review fraud flags')->name('fraud-flags.index');
        Route::patch('fraud-flags/{fraudFlag}', [FraudFlagController::class, 'update'])->middleware('role_permission:review fraud flags')->name('fraud-flags.update');
        Route::get('announcements/create', [AnnouncementController::class, 'create'])->middleware('role_permission:send announcements')->name('announcements.create');
        Route::post('announcements', [AnnouncementController::class, 'store'])->middleware('role_permission:send announcements')->name('announcements.store');
        Route::get('role-permissions', [RolePermissionController::class, 'index'])->name('role-permissions.index');
        Route::put('role-permissions/{role}', [RolePermissionController::class, 'update'])->name('role-permissions.update');
    });
});
