import { Head, Link } from "@inertiajs/react";
import { Eye, Search } from "lucide-react";
import { InstructorLayout } from "@/layouts/instructor-layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

interface RecordItem { id: number; status: string; recorded_at: string; distance_meters: string; accuracy_meters: string; needs_review: boolean; photo?: { id: number } | null }
interface Participant { id: number; name: string; participant_number: string | null; morning: RecordItem | null; afternoon: RecordItem | null; leave: { type: string; reason: string } | null }
interface TrainingClass { id: number; name: string; training_batch: { name: string; training_program: { name: string } } }

const labels: Record<string, string> = { on_time: "Tepat waktu", late: "Terlambat", present: "Hadir", early_leave: "Pulang cepat", needs_verification: "Perlu verifikasi", outside_schedule: "Di luar jadwal" };
function AttendanceCell({ record, leave }: { record: RecordItem | null; leave: Participant["leave"] }) { if (leave) return <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">{leave.type === "sick" ? "Sakit" : "Izin"}</span>; if (!record) return <span className="rounded-full bg-red-50 px-3 py-1 text-xs font-semibold text-red-700">Belum absen</span>; return <div className="flex items-center gap-2"><div><span className="font-semibold">{labels[record.status] || record.status}</span><small className="block text-muted-foreground">{new Date(record.recorded_at).toLocaleTimeString("id-ID")} · {record.distance_meters} m</small></div><Button asChild variant="ghost" size="icon"><Link href={route("instructor.attendances.show", record.id)} aria-label="Lihat detail"><Eye className="size-4" /></Link></Button></div>; }

export default function Index({ classes, selectedClass, schedule, participants, filters }: { classes: TrainingClass[]; selectedClass: TrainingClass | null; schedule: { subject: string | null; start_time: string; end_time: string } | null; participants: Participant[]; filters: { date: string; class_id: number | null; search: string } }) {
    return <InstructorLayout title="Monitoring absensi"><Head title="Monitoring Absensi" />
        <form method="get" action={route("instructor.attendances.index")} className="grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[1fr_1fr_1fr_auto]"><label className="grid gap-1 text-sm font-semibold">Tanggal<Input type="date" name="date" defaultValue={filters.date} /></label><label className="grid gap-1 text-sm font-semibold">Kelas<select name="class_id" defaultValue={filters.class_id || ""} className="h-10 rounded-lg border bg-white px-3">{classes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Cari peserta<Input name="search" defaultValue={filters.search} placeholder="Nama peserta" /></label><Button className="self-end"><Search />Tampilkan</Button></form>
        {selectedClass && <div className="mt-4 rounded-xl bg-blue-50 p-4 text-sm"><strong>{selectedClass.training_batch.training_program.name} · {selectedClass.name}</strong><p>{schedule ? `${schedule.subject || "Pelatihan"} · ${schedule.start_time.slice(0, 5)}–${schedule.end_time.slice(0, 5)}` : "Tidak ada jadwal pada tanggal ini."}</p></div>}
        <div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-100"><tr><th className="p-4 text-left">Nomor</th><th className="p-4 text-left">Peserta</th><th className="p-4 text-left">Pagi</th><th className="p-4 text-left">Sore</th><th className="p-4 text-left">Status harian</th></tr></thead><tbody>{participants.map(item => <tr key={item.id} className="border-t"><td className="p-4">{item.participant_number || "-"}</td><td className="p-4 font-semibold">{item.name}</td><td className="p-4"><AttendanceCell record={item.morning} leave={item.leave} /></td><td className="p-4"><AttendanceCell record={item.afternoon} leave={item.leave} /></td><td className="p-4">{item.leave ? (item.leave.type === "sick" ? "Sakit" : "Izin") : item.morning && item.afternoon ? "Lengkap" : item.morning || item.afternoon ? "Belum lengkap" : "Alfa/belum hadir"}</td></tr>)}{participants.length === 0 && <tr><td colSpan={5} className="p-10 text-center text-muted-foreground">Tidak ada peserta pada kelas ini.</td></tr>}</tbody></table></div>
    </InstructorLayout>;
}
