import { Head, Link } from "@inertiajs/react";
import { motion } from "motion/react";
import { AlertTriangle, CheckCircle2, Clock3, FileClock, LogIn, LogOut, UserCheck, UsersRound } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { AdminLayout } from "@/layouts/admin-layout";
import { staggerContainer } from "@/lib/motion";

interface Stats { participants:number;pending:number;present:number;late:number;leave:number;sick:number;notCheckedIn:number;notCheckedOut:number;attendanceRate:number;reviews:number;pendingLeaves:number }
export default function Dashboard({stats,trend,programs}:{stats:Stats;trend:{date:string;total:number}[];programs:{id:number;name:string;batches_count:number}[]}){
 const cards=[{label:"Peserta aktif",value:stats.participants,icon:UsersRound},{label:"Hadir hari ini",value:stats.present,icon:CheckCircle2,tone:"green" as const},{label:"Terlambat",value:stats.late,icon:Clock3,tone:"amber" as const},{label:"Belum masuk",value:stats.notCheckedIn,icon:LogIn,tone:"red" as const},{label:"Belum pulang",value:stats.notCheckedOut,icon:LogOut,tone:"amber" as const},{label:"Izin / sakit",value:`${stats.leave} / ${stats.sick}`,icon:FileClock},{label:"Menunggu verifikasi",value:stats.pending,icon:UserCheck,tone:"amber" as const},{label:"Perlu ditinjau",value:stats.reviews,icon:AlertTriangle,tone:"red" as const}];
 return <AdminLayout title="Dashboard"><Head title="Dashboard Admin"/><PageHeader eyebrow="DASHBOARD" title="Ringkasan kehadiran" description={`Kehadiran hari ini ${stats.attendanceRate}% · data berdasarkan waktu server.`}/><motion.div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" initial="hidden" animate="visible" variants={staggerContainer}>{cards.map(item=><StatCard key={item.label} {...item}/>)}</motion.div><div className="mt-6 grid gap-5 xl:grid-cols-[2fr_1fr]"><Card><CardContent><h2 className="font-semibold">Tren kehadiran 7 hari</h2><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date"/><YAxis allowDecimals={false}/><Tooltip/><Area type="monotone" dataKey="total" stroke="#2563eb" fill="#dbeafe" name="Peserta"/></AreaChart></ResponsiveContainer></div></CardContent></Card><Card><CardContent><div className="flex items-center justify-between"><h2 className="font-semibold">Perlu tindakan</h2><Button asChild size="sm" variant="outline"><Link href={route("admin.leave-requests.index")}>Buka</Link></Button></div><div className="mt-4 grid gap-3"><div className="rounded-xl bg-amber-50 p-4"><strong className="text-2xl text-amber-800">{stats.pendingLeaves}</strong><p className="text-sm text-amber-700">Pengajuan izin/sakit menunggu</p></div><div className="rounded-xl bg-red-50 p-4"><strong className="text-2xl text-red-800">{stats.reviews}</strong><p className="text-sm text-red-700">Absensi mencurigakan</p></div></div><h3 className="mt-6 text-sm font-semibold">Program aktif</h3><div className="mt-2 divide-y">{programs.map(p=><div key={p.id} className="flex justify-between py-2 text-sm"><span>{p.name}</span><span className="text-muted-foreground">{p.batches_count} angkatan</span></div>)}</div></CardContent></Card></div></AdminLayout>;
}
