import { Head } from "@inertiajs/react";
import { Download, FileText, Search } from "lucide-react";
import { InstructorLayout } from "@/layouts/instructor-layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { StatCard } from "@/components/stat-card";
import type { Paginated } from "@/types";

interface Row { id: number; attendance_date: string; type: string; status: string; recorded_at: string; user: { name: string; participant_profile?: { participant_number: string } | null }; training_schedule: { training_class: { name: string } }; attendance_location: { name: string } }
export default function Index({ rows, summary, classes, filters }: { rows: Paginated<Row>; summary: { total: number; morning: number; afternoon: number; late: number }; classes: { id: number; name: string }[]; filters: Record<string, string> }) { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value).map(([key, value]) => [key, String(value)])).toString(); return <InstructorLayout title="Rekap kelas"><Head title="Rekap Kelas" /><div className="grid gap-3 sm:grid-cols-4"><StatCard label="Total catatan" value={summary.total} icon={FileText} /><StatCard label="Absen pagi" value={summary.morning} icon={FileText} /><StatCard label="Absen sore" value={summary.afternoon} icon={FileText} /><StatCard label="Terlambat" value={summary.late} icon={FileText} tone="red" /></div><form method="get" action={route("instructor.reports.index")} className="mt-4 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-4"><label className="grid gap-1 text-sm font-semibold">Mulai<Input type="date" name="start_date" defaultValue={filters.start_date} /></label><label className="grid gap-1 text-sm font-semibold">Sampai<Input type="date" name="end_date" defaultValue={filters.end_date} /></label><label className="grid gap-1 text-sm font-semibold">Kelas<select name="class_id" defaultValue={filters.class_id || ""} className="h-10 rounded-lg border bg-white px-3"><option value="">Semua kelas</option>{classes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Button className="self-end"><Search />Tampilkan</Button></form><div className="mt-3 flex flex-wrap gap-2"><Button asChild><a href={`${route("instructor.reports.excel")}?${query}`}><Download />Excel</a></Button><Button asChild variant="outline"><a href={`${route("instructor.reports.pdf")}?${query}`}><Download />PDF</a></Button></div><div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-100"><tr><th className="p-4 text-left">Tanggal</th><th className="p-4 text-left">Peserta</th><th className="p-4 text-left">Kelas</th><th className="p-4 text-left">Sesi</th><th className="p-4 text-left">Status</th><th className="p-4 text-left">Waktu</th></tr></thead><tbody>{rows.data.map(item => <tr key={item.id} className="border-t"><td className="p-4">{item.attendance_date}</td><td className="p-4"><strong>{item.user.name}</strong><small className="block">{item.user.participant_profile?.participant_number}</small></td><td className="p-4">{item.training_schedule.training_class.name}</td><td className="p-4">{item.type === "morning" ? "Pagi" : "Sore"}</td><td className="p-4">{item.status}</td><td className="p-4">{new Date(item.recorded_at).toLocaleString("id-ID")}</td></tr>)}</tbody></table></div></InstructorLayout>; }
