import { Head, Link, router } from '@inertiajs/react';
import { ShieldAlert } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { ReasonDialog } from '@/components/reason-dialog';
import { Button } from '@/components/ui/button';
import { AdminLayout } from '@/layouts/admin-layout';

interface Flag { id: number; reason: string; severity: string; status: string; metadata: Record<string, unknown> | null; review_notes: string | null; user: { name: string; participant_profile?: { participant_number: string } | null }; attendance?: { id: number; attendance_date: string; type: string; distance_meters: string; accuracy_meters: string } | null }
interface PageLink { url: string | null; label: string; active: boolean }

export default function Flags({ flags, filters }: { flags: { data: Flag[]; links: PageLink[] }; filters: Record<string, string> }) {
    function review(flag: Flag, status: 'reviewed' | 'dismissed', notes: string) { router.patch(route('admin.fraud-flags.update', flag.id), { status, review_notes: notes }, { preserveScroll: true }); }
    const labels: Record<string, string> = { open: 'Terbuka', reviewed: 'Ditinjau', dismissed: 'Diabaikan' };

    return <AdminLayout title="Peninjauan Fraud"><Head title="Peninjauan Fraud"/><PageHeader eyebrow="KEAMANAN" title="Absensi mencurigakan" description="Flag adalah sinyal untuk ditinjau dan tidak otomatis membuktikan kecurangan."/><div className="mt-5 flex flex-wrap gap-2">{['', 'open', 'reviewed', 'dismissed'].map((status) => <Button key={status} size="sm" variant={(filters.status ?? '') === status ? 'default' : 'outline'} onClick={() => router.get(route('admin.fraud-flags.index'), status ? { status } : {})}>{status ? labels[status] : 'Semua'}</Button>)}</div><div className="mt-5 grid gap-3">{flags.data.map((flag) => <article key={flag.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="flex items-center gap-2 font-bold"><ShieldAlert className="size-5 text-red-600"/>{flag.reason}</p><p className="mt-1 text-sm">{flag.user.name} · {flag.user.participant_profile?.participant_number}</p></div><span className="h-fit rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700">{flag.severity} · {labels[flag.status] ?? flag.status}</span></div>{flag.attendance && <p className="mt-3 text-sm text-muted-foreground">{flag.attendance.attendance_date} · {flag.attendance.type} · jarak {flag.attendance.distance_meters} m · akurasi ±{flag.attendance.accuracy_meters} m</p>}<pre className="mt-3 overflow-auto rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(flag.metadata, null, 2)}</pre>{flag.status === 'open' && <div className="mt-3 flex flex-wrap gap-2"><ReasonDialog trigger={<Button size="sm">Tandai ditinjau</Button>} title="Selesaikan peninjauan" description="Catat hasil pemeriksaan agar keputusan dapat diaudit." label="Catatan hasil peninjauan" confirmLabel="Simpan hasil" onConfirm={(notes) => review(flag, 'reviewed', notes)}/><ReasonDialog trigger={<Button size="sm" variant="outline">Abaikan flag</Button>} title="Abaikan fraud flag" description="Berikan alasan mengapa indikator ini dinilai bukan kecurangan." label="Alasan mengabaikan" confirmLabel="Abaikan" onConfirm={(notes) => review(flag, 'dismissed', notes)}/></div>}{flag.review_notes && <p className="mt-3 text-sm">Catatan: {flag.review_notes}</p>}</article>)}{flags.data.length === 0 && <div className="rounded-xl border bg-white p-12 text-center text-muted-foreground">Tidak ada fraud flag pada filter ini.</div>}{flags.links.length > 3 && <nav className="flex flex-wrap gap-2" aria-label="Paginasi fraud flag">{flags.links.map((link, index) => <Button key={index} asChild={Boolean(link.url)} size="sm" variant={link.active ? 'default' : 'outline'} disabled={!link.url}>{link.url ? <Link href={link.url} preserveScroll dangerouslySetInnerHTML={{ __html: link.label }}/> : <span dangerouslySetInnerHTML={{ __html: link.label }}/>}</Button>)}</nav>}</div></AdminLayout>;
}
